### ISSUE TITLE
Can't use phing.listener.DefaultLogger

### ISSUE THREAD

**Issue by AKhrulev** [phingofficial/guide#31]
[Attempt to use DefaultLogger](https://www.phing.info/guide/chunkhtml/DefaultLogger.html)

`-logger phing.listener.DefaultLogger`

 causes error:

> Phing\Exception\ConfigurationException: Error importing phing.listener.DefaultLogger.php in phar://C:/phing/phing-3.0.0-RC1.phar/src/Phing/Phing.php:1395

**Comment by mrook** [comment]
Hi @AKhrulev, this class was moved to `Phing\Listener\DefaultLogger`. We'll check & update the documentation.

**Comment by mrook** [comment]
Made some changes in https://github.com/phingofficial/guide/commit/b0ae5aa7b82ae408f7bf35301467bdeb15df8e02 and https://github.com/phingofficial/guide/commit/cf8382a28c5df5315a1c9339d11dbae352f565ee

**Comment by mrook** [comment]
And https://github.com/phingofficial/phing/commit/c3e2a9211631ece201006b83c1e5b2aebeba0ff9
