### ISSUE TITLE
Documentation refactoring

### ISSUE THREAD

**Issue by jawira** [phingofficial/guide#33]
Hi, currently I find very hard to update documentation, more specifically _Optional Tasks_ file `source/appendixes/optionaltasks.xml` is very large.

So what do you think about splitting this file in many files (one per task)? 

I can take care of this if you agree. Thanks :)

**Comment by mrook** [comment]
Yep, you're totally right! Appreciate any help :-)

**Comment by mrook** [comment]
Resolved in #34.
